### PR TITLE
[DO NOT MERGE] rake tasks to start/stop workers

### PR DESCRIPTION
**Pull request by tampakis**
Restart resque workers on cap deploy. Advances #30.

### CODE REVIEW

**Comment by jpstroop** [comment]
This seems :+1: to me, but would like @escowles or @tpendragon to have a look.

**Comment by tpendragon** [comment]
Only concern I'd have is this is a bit different than how the other projects do it, which rely on upstart scripts.

**Comment by jpstroop** [comment]
Is this ever going to be merged, or should we close it?

**Comment by kevinreiss** [comment]
@tampakis we need to work out how we want to manage a queue for this application.

**Comment by jpstroop** [comment]
Isn't there a queue for generating the subject browse lists already?

**Comment by jpstroop** [comment]
If starting/stopping workers is the issue we should do whatever the proc machines are doing and keep things consistent.

**Comment by escowles** [comment]
Yes, we should probably do this with cap like we do in plum: https://github.com/pulibrary/plum/blob/master/config/deploy.rb#L61

**Comment by tampakis** [comment]
Woah we can finally close this PR, we don't use resque anymore!

**Pull request closed without merging**
