### PR TITLE
Only run full dump transfer job if it's a full dump job

### LINKED ISSUE #977: Use job name in AwsSqsPoller to determine what sort of dump type to create.
For now this probably just means filtering out any job that doesn't have the full dump job title. Can build forward as part of incremental index work #927.

job names are:
* "Publishing Platform Job General Publishing via FTP" (full dump job)
* "Publishing Platform Job Incremental Publishing via FTP" (incremental dump job)

### PR DESCRIPTION
**Pull request by hackartisan**
closes #977

The incremental job will be implemented with #927 and #809

### CODE REVIEW

**Review by christinach — DISMISSED** [review]

**Comment by christinach** [comment]
@hackartisan a rubocop thing

**Comment by hackartisan** [comment]
@christinach that would have broken it actually; thanks rubocop! it's fixed now.

**Comment by hackartisan** [comment]
wait it's still not right give me a second.

**Comment by hackartisan** [comment]
@christinach okay now it's fixed thanks!

**Review by christinach — APPROVED** [review]

**Pull request merged**
