### PR TITLE
Integrates support for Lando

### LINKED ISSUE #865: Use lando for postgres

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #865 by integrating Lando support and updating the CircleCI config. (also inserts stubs into the request test suite for the `BibliographicController` actions)

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
I tried this briefly and got errors about the database not existing. I see the task calling `db:create` so I'm not sure why it isn't working :(

**Review by christinach — CHANGES_REQUESTED** [review]
@jrgriffiniii I deleted from my local the dev and test dbs I had in postgres to have a clean start. I ran `bundle exec rake marc_liberation:server:start` and I get the error `PG::ConnectionBad: FATAL:  database "marc_liberation_dev" does not exist`.

**Review by christinach — COMMENTED** [review]
I also noticed that lando will not start when I do `lando start` or `lando rebuild.` When I run `lando restart -vvv` I get some debug information `debug:  message=Cannot read property 'split' of undefined, stack=TypeError: Cannot read property 'split' of undefined`. It might be helpful for you to troubleshoot.

**Comment by jrgriffiniii** [comment]
I wanted to refactor one area of the code and ensure that the processing for holding location values can be run even when `lando` isn't installed. This is ready for another review please.

**Review by christinach — APPROVED** [review]
It works for me @jrgriffiniii . Thank you very much!

**Comment by jrgriffiniii** [comment]
Thank you very much for reviewing this @christinach , I will merge this and proceed with looking to assist with #940

**Review by hackartisan — CHANGES_REQUESTED** [review]
Lando spins up but I have some failures in the devise specs locally (see gist) I wonder if we should try incrementing the circleci cache and make sure the tests still pass.

https://gist.github.com/hackartisan/11a3ff6cb9f5d94dc587dd82d9f0bd46

seed for those failures was `41523` -- it's possible we might have to wipe out the DB and then run the tests with that seed

**Comment by christinach** [comment]
@jrgriffiniii after @hackartisan mentioned it I remember that I got the same errors but when I ran the test a second time I had no errors.

**Comment by christinach** [comment]
@jrgriffiniii thank you again! There are no spec failures now. The only error that I keep seeing but it doesn't break the test is :`error: Cannot read property 'split' of undefined` followed by the warning `[2020-12-14T14:08:42.257310 #18775]  WARN -- : Failed to start the container services using Lando: A JSON text must at least contain two octets!`

**Comment by jrgriffiniii** [comment]
I am sorry for this error, did reproduce the failing tests. https://github.com/pulibrary/marc_liberation/pull/930/commits/7306bea48814d3e012b3b77cda95d700dc598027 remedied this for me locally.

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
